# Generated by Django 2.1.1 on 2018-09-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=25)),
                ('twitt_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
